apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec:
  # DO NOT INCREASE REPLICA COUNT
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr-deployment
  template:
    metadata:
      labels:
        app: k8s-bigip-ctlr-deployment
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      # permissions
      containers:
        - name: cntr-ingress-svcs
          image: registry.connect.redhat.com/f5networks/cntr-ingress-svcs:latest
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            # See the k8s-bigip-ctlr documentation for information about
            # all config options
            # https://clouddocs.f5.com/containers/latest/
              "--bigip-username=$(BIGIP_USERNAME)",
              "--bigip-password=$(BIGIP_PASSWORD)",
              "--bigip-url=10.1.1.5",
              "--bigip-partition=ocp",
              "--namespace=default",
              "--pool-member-type=cluster",
              "--enable-ipv6=false",
              #"--openshift-sdn-name=/Common/okd-tunnel",
              "--log-level=DEBUG",
              "--insecure=true",
              "--manage-routes=true",
              "--static-routing-mode=true",
              "--extended-spec-configmap=kube-system/extended-cm",
              "--route-vserver-addr=10.1.10.11",
              "--orchestration-cni=ovn-k8s",
              "--route-http-vserver=ocp_http_vs",
              "--route-https-vserver=ocp_https_vs",        
              #"--override-as3-declaration=default/cafe-override",
              "--as3-validation=true",
              "--log-as3-response=true",
              "--disable-teems=true",
          ]
      serviceAccountName: k8s-bigip-ctlr
